<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<!-- EF Core -->
		<PackageReference Include="ClosedXML" Version="0.102.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<!-- MySQL Provider -->
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />

		<!-- Identity -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />

		<!-- JWT -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />

		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.2" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.5.2" />

		<!-- Serilog -->
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />

		<!-- PDF Generation -->
		<PackageReference Include="QuestPDF" Version="2024.10.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Project.Application\Project.Application.csproj" />
	  <ProjectReference Include="..\Project.Domain\Project.Domain.csproj" />
	</ItemGroup>


</Project>
